# Generated by Django 4.2.6 on 2023-11-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokupka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(default='', max_length=256)),
                ('quantity', models.FloatField(default='', max_length=256)),
                ('price', models.FloatField(default='', max_length=256)),
                ('category', models.CharField(default='', max_length=256)),
                ('picture', models.FileField(upload_to='')),
            ],
        ),
    ]
